myshop/myshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myshop/shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.ItemList.as_view(), name='item_list'),
    path('<int:pk>/', views.ItemDetail.as_view(), name='item_detail'),
    path('sale_list/', views.SaleList.as_view(), name='sale_list'),
    path('change_price/', views.HistoryPrice.as_view(), name='history_price'),
]

myshop/shop/models.py
from decimal import Decimal
from django.urls import reverse
from django.core.validators import MinValueValidator
from django.db import models
from django.db.models.signals import post_save, pre_save
from django.db.models import F
from django.dispatch import receiver


class Item(models.Model):
    item_id = models.AutoField(primary_key=True)
    item_name = models.CharField(max_length=120, verbose_name='Товар')
    quantity = models.PositiveSmallIntegerField(verbose_name='Количество')
    price = models.DecimalField(max_digits=10,
                                decimal_places=2,
                                validators=[MinValueValidator(Decimal('0.01'))],
                                verbose_name='цена')
    description = models.TextField(blank=True)
    available = models.BooleanField(default=True)
    image = models.ImageField(upload_to='products', blank=True)

    class Meta:
        ordering = ('item_name',)

    def __str__(self):
        return self.item_name

    def get_absolute_url(self):
        return reverse('shop:item_detail',
                       args=[self.item_id])


class Employee(models.Model):
    employee_id = models.AutoField(primary_key=True)
    employee_name = models.CharField(max_length=60, verbose_name='Продавец')
    items = models.ManyToManyField(Item, related_name='Товары')

    class Meta:
        ordering = ('employee_name',)

    def __str__(self):
        return self.employee_name


class Sale(models.Model):
    sale_id = models.AutoField(primary_key=True)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    quantity = models.PositiveSmallIntegerField(verbose_name='Количество')
    price = models.DecimalField(max_digits=10,
                                decimal_places=2,
                                validators=[MinValueValidator(Decimal('0.01'))],
                                verbose_name='Цена')
    created_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created_date',)

    def __str__(self):
        return 'Order {}'.format(self.sale_id)

    def get_cost(self):
        return self.price * self.quantity


class PriceHistory(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10,
                                    decimal_places=2,
                                    validators=[MinValueValidator(Decimal('0.01'))],
                                    verbose_name='Цена')
    created_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created_date',)

myshop/shop/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect, HttpResponse
from django.views.generic import ListView
from django.views.generic.edit import FormView
from .models import Item, Sale, PriceHistory
from .form import CreateSaleForm


class ItemList(ListView):
    model = Item
    paginate_by = 8
    context_object_name = "items"
    template_name = "base.html"

    def get_queryset(self):
        queryset = self.model._default_manager.filter(available=True).exclude(quantity=0)
        return queryset


class ItemDetail(FormView):
    form_class = CreateSaleForm
    template_name = 'product/detail.html'
    success_url = '/'

    def setup(self, request, *args, **kwargs):
        super(ItemDetail, self).setup(request, *args, **kwargs)
        self.item = Item.objects.get(pk=self.kwargs['pk'])


    def get_form_kwargs(self):
        kwargs = super(ItemDetail, self).get_form_kwargs()
        kwargs['item'] = self.item
        return kwargs

    def form_valid(self, form):
        super(ItemDetail, self).form_valid(form)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(self.success_url)
        else:
            self.form_invalid(form)

    def form_invalid(self, form):
        return HttpResponse("form is invalid.. ")


class SaleList(LoginRequiredMixin, ListView):
    model = Sale
    paginate_by = 5
    context_object_name = "sales"
    template_name = "sale/salelist.html"


class HistoryPrice(LoginRequiredMixin, ListView):
    model = PriceHistory
    paginate_by = 5
    context_object_name = "history_price"
    template_name = "history_price/history_price_list.html"

myshop/shop/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}This amazing shop{% endblock %}</title>
    <link href="{% static "css/base.css" %}" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

</head>
<body>
    <div id="header">
        <a href="/" class="logo"><h1>My shop</h1></a>
        <ul class="auth">
          {% if request.user.is_authenticated %}
              <li>User: <a href="{% url "shop:sale_list" %}" >{{ user.get_username }}</a></li>
              <li><a href="{% url "shop:history_price" %}">History Price</a></li>
              <li><a href="{% url "logout" %}">Logout</a></li>
          {% else %}
              <li><a href="{% url "login" %}">Login</a></li>
          {% endif %}
        </ul>
    </div>
    <div id="content">
        {% block content %}
            <h1>Items</h1>
                {% for item in items %}
                    <div class="item">
                        <a href="{{ item.get_absolute_url }}">
                        <img class="img-thumbnail" src="{% if item.image %}{{ item.image.url }}
                                  {% else %}{% static "img/no_image.png" %}
                                  {% endif %}">
                        </a>
                        <a href="{{ item.get_absolute_url }}"><h2>{{ item.item_name }}</h2></a> ${{ item.price }}
                        <br>
                        <a href="{{ item.get_absolute_url }}">
                            <button type="button" class="btn btn-primary btn-sm">Buy It</button>
                        </a>
                    </div>
                {% endfor %}
         {% endblock %}
    </div>
    {% block paginator %}
    <div class="footer">
    <nav aria-label="Page navigation">
    {% if is_paginated %}
        <ul class="pagination">
        {% if page_obj.has_previous %}
            <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
            </li>
        {% else %}
            <li class="page-item disabled">
            <a class="page-link" href="#">&laquo;</a>
            </li>
        {% endif %}
        {% for i in paginator.page_range %}
            {% if page_obj.number == i %}
                <li class="page-item"><a class="page-link active">{{ i }}</a></li>
            {% else %}
                <li class="page-item">
                <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                </li>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
            <li class="page-item">
            <a href="?page={{page_obj.next_page_number}}" class="page-link">&raquo;</a>
            </li>
        {% else %}
            <li class="page-item disabled">
            <a class="page-link">&raquo;</a>
            </li>
        {% endif %}
        </ul>
    {% endif %}
    </nav>
    </div>
    <div class="time">
      {{ time }}
    </div>
    {% endblock %}
</body>
</html>

myshop/shop/templates/history_price/history_price_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}Price History{%  endblock %}


{% block content %}
  <br>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Item</th>
        <th scope="col">Price</th>
        <th scope="col">Date</th>
      </tr>
    </thead>
    <tbody>
      {% for item in history_price %}
        <tr>
          <td>{{ item.item }}</td>
          <td>{{ item.price }}</td>
          <td>{{ item.created_date }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

myshop/shop/templates/product/detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}{{ item.item_name }}{% endblock %}
{% block content %}
    {% with form.item as item %}
        <div class="item">
            <img src="{% if item.image %}{{ item.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
            <h1>{{ item.item_name }}</h1>
            <p class="price">${{ item.price }}</p>
            <form class="form-range" action="." method="post">
                {% csrf_token %}
                {{ form.employee }}
                {{ form.quantity }}
                <input type="submit" value="Buy It">
            </form>
        </div>
        <div class="description">
            <h6>{{ item.description }}</h6>
        </div>
    {% endwith %}
{% endblock %}

myshop/shop/templates/sale/salelist.html
{% extends "base.html" %}
{% load static %}

{% block title %}Sales{%  endblock %}


{% block content %}
  <br>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Date</th>
        <th>Item</th>
        <th>Price</th>
        <th>Quantity</th>
        <th>Employee</th>
        <th>Total</th>
      </tr>
    </thead>
    <tbody>
      {% for sale in sales %}
        <tr>
          <td>{{ sale.created_date }}</td>
          <td>{{ sale.item }}</td>
          <td>{{ sale.price }}</td>
          <td>{{ sale.quantity }}</td>
          <td>{{ sale.employee }}</td>
          <td>{{ sale.get_cost}}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}